name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      BACKEND_IMAGE: mojeshreddy/jobapp-backend:latest
      FRONTEND_IMAGE: mojeshreddy/jobapp-frontend:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Backend Build & Test
      - name: Backend - Install & Test
        working-directory: ./backend
        run: |
          npm install
          npm test || echo "No tests found"

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Backend Docker image
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}

      # Build and Push Frontend Image
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend   # change if your frontend folder path is different
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}

      # Optional: Deployment
      # - name: Deploy to server
      #   run: |
      #     ssh user@your-server "docker pull $BACKEND_IMAGE && docker pull $FRONTEND_IMAGE && docker-compose up -d"
